services:
  Shared.Logger:
    class: ../../../contexts/shared/infrastructure/logger/WinstonLogger
    arguments: []

  Shared.CommandHandlers:
    class: ../../../contexts/shared/infrastructure/command-bus/CommandHandlers
    arguments: ["!tagged commandHandler"]
  Shared.Domain.CommandBus:
    class: "../../../contexts/shared/infrastructure/command-bus/InMemoryCommandBus"
    arguments: ["@Shared.CommandHandlers"]

  Shared.QueryHandlers:
    class: ../../../contexts/shared/infrastructure/query-bus/QueryHandlers
    arguments: ["!tagged queryHandler"]

  Shared.Domain.QueryBus:
    class: ../../../contexts/shared/infrastructure/query-bus/InMemoryQueryBus
    arguments: ["@Shared.QueryHandlers"]

  Shared.Mongo.Config.NFC:
    factory:
      class: ../../../contexts/shared/infrastructure/persistance/mongo/MongoConfigFactory
      method: "createConfig"
    arguments: ["nfc-backend"]

  Shared.Mongo.Connection.Manager.NFC:
    factory:
      class: ../../../contexts/shared/infrastructure/persistance/mongo/MongoClientFactory
      method: "createClient"
    arguments: ["nfc-backend", "@Shared.Mongo.Config.NFC"]

  Shared.Domain.JwtService:
    class: ../../../contexts/shared/infrastructure/jwt/JsonWebTokenService
    arguments: ["%jwt.secret%"]

  Shared.AuthMiddleware:
    class: ../../../app/middlewares/AuthMiddleware
    arguments: ["@Shared.Domain.JwtService"]

  Shared.TemplateService:
    class: ../../../contexts/shared/infrastructure/template/HtmlTemplateService
    arguments: []
